### ISSUE TITLE
Clicking on the slider rather than dragging

### ISSUE THREAD

**Issue by leemthai** [TomJGooding/textual-slider#43]
Love the widget. Just wondering if you ever planned to upgrade it so clicks on the widget could also server to move/set the slider?

Thanks again for a great widget!

**Comment by TomJGooding** [comment]
Thanks @leemthai! Honestly I haven't looked at this project for a while, but clicking to quickly move the slider makes perfect sense. 

This might be tricky due to the limitations of working with character cells in the terminal, but I will definitely try to find some time to implement this.

**Comment by leemthai** [comment]
Thanks man! I'll leave this open for a day or two. I might have something to show you (presuming it works lol). Cheers.
